### ISSUE TITLE
mpv shaders : nlmeans_lgc doesn't upscale chroma plane

### ISSUE THREAD

**Issue by hooke007** [AN3223/dotfiles#12]
https://github.com/AN3223/dotfiles/commit/8c7b69683f33c6d06bf22ce1db7c0ab2d4b269d4

It only tries to blur some color but doesn't change anything else.

You seems to forget to handle the size after chroma bind?

**Comment by AN3223** [comment]
Gah, you're right. I've moved it back to experimental now. Something is very wrong with the benchmarks.

**Comment by AN3223** [comment]
I'll close this for now since LGC has been moved back to experimental, I won't move it out until all of its problems are fixed.
